name: OptimisedAction
on:
  push:
    branches:
      - main

jobs:
  build-cpputest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check for cpputest folder
      run: |
        if [ ! -d "cpputest" ]; then
          echo "cpputest folder not found."
          echo "cpputest_exists=false" >> $GITHUB_ENV
        else
          echo "cpputest folder exists."
          echo "cpputest_exists=true" >> $GITHUB_ENV
        fi
    
    - name: Set up dependencies (If necessary)
      if: env.cpputest_exists == 'false'
      run: |
        git clone https://github.com/cpputest/cpputest.git
        cd cpputest/cpputest_build
        autoreconf .. -i
        ../configure
        make
        cd ../..
    
    - name: Start Tests
      run: |
        echo "Starting tests"
        make -C TDD4ES/tests -f tmpMakefile.mk

    - name: Run tests
      run: |
        echo "Running test cases"
        ./TDD4ES/tests/ez.testcase
      

    
    